name: test
run-name: Testeando
on: [push]
jobs:
  compilar:
    runs-on: ubuntu-latest
    steps:
      - name : Echo the message 
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      # - uses: actions/checkout@v3
      # - run: pwd
      # - run: ls
      # - run: cd ./tp-ahorcado
      # - run: pwd
      # - run: npm test
