name: test
run-name: Testeando
on: [push]
jobs:
  compilar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: node ./tp-ahorcado/src/ahorcado.js
      - run: npm install -g jest
      - run: npm run jest
